import asyncio
import signal

from letta import ChatMemory, EmbeddingConfig, LLMConfig
from letta.prompts import gpt_system
from letta.schemas.llm_config import LLMConfig
from letta.schemas.tool_rule import TerminalToolRule

from yanara.api.wechat_api.__main__ import monitor_wechat_messages, stop_loop
from yanara.api.wechat_api.wechat_message_manager import WeChatMessageManager
from yanara.globals import client
from yanara.util.decorators import entry


def create_yanara() -> str:
    agent_state = client.create_agent(
        # agent's name (unique per-user, autogenerated if not provided)
        name="yanara",
        # in-context memory representation with human/persona blocks
        memory=ChatMemory(human="Name: Sarah", persona="You are a helpful assistant that loves emojis"),
        # system instructions for the agent (defaults to `memgpt_chat`)
        system=gpt_system.get_system_text("memgpt_chat"),
        # whether to include base letta tools (default: True)
        include_base_tools=True,
        # list of additional tools (by name) to add to the agent
        tools=[],
    )
    print(f"Created agent with name {agent_state.name} and unique ID {agent_state.id}")
    return agent_state.id


@entry
def main():
    agent_id = None
    if client.agent_exists(agent_name="yanara"):
        print("Agent 'yanara' already exists. Skipping agent creation.")
        agent_id = client.get_agent_by_name("yanara").id
    else:
        agent_id = create_yanara()

    stop_flag = asyncio.Event()

    # Register the signal handler
    signal.signal(signal.SIGINT, lambda s, f: stop_loop(s, f, stop_flag))
    signal.signal(signal.SIGTERM, lambda s, f: stop_loop(s, f, stop_flag))

    asyncio.run(monitor_wechat_messages(agent_id, stop_flag))
